spring.application.name=ChatApplication

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true
spring.datasource.username=postgres.vrmtttcsijyfcbewyyda
spring.datasource.password=Ajay9291@$1

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.preparedStatementCacheQueries=0
spring.datasource.hikari.data-source-properties.preparedStatementCacheSizeMiB=0

jwt.secretkey=9f8c7a6b5d4e3f2a1c0b9e8d7f6a5b4c9f8c7a6b5d4e3f2a1c0b9e8d7f6a5b4c
jwt.expiration=86400000